javascripts:
	ender build jeesh --output ../js/lib.js

bootstrap:
	cd bootstrap && make bootstrap
	cp bootstrap/bootstrap/css/*.css ../css/
	cp bootstrap/bootstrap/js/*.js ../js/
	cp bootstrap/bootstrap/img/*.png ../img/
	

.PHONY: bootstrap